apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: config-map-frontend
data:
  default.conf: |
    map $http_authorization $valid_key {
      include /etc/config/secret/*.conf;
      default unauthenticated;
    }
    server {
      listen 80 default_server;
      location / {
        if ($valid_key != pass) {
          return 401;
        }
        proxy_pass http://service-ollama:11434;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        # Setting proxy_read_timeout needs to be set to the same value as in the
        # ingress-webapp.yaml file. Set timeout high so the stream is not killed
        # prematurely.
        proxy_read_timeout 3600s;
        # Setting proxy_send_timeout needs to be set to the same value as in the
        # ingress-webapp.yaml file. For large multimodal requests, set the send
        # timeout conservatively high.
        proxy_send_timeout 300s;
        # Disable proxy buffering for Server Side Event streaming which forces
        # Nginx to pass data to the client instantly as it is generated. When
        # buffering is enabled, nginx re-chunks the stream arbitrarily, breaking
        # markdown tokens across chunk boundaries. Disabling the proxy cache
        # prevents Nginx from caching the stream data, which would otherwise
        # corrupt the real-time timeline.
        # See: https://github.com/open-webui/open-webui/discussions/20588#discussioncomment-15469248
        proxy_buffering off;
        proxy_cache off;
      }
    }
