apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Sometimes external secrets are refered to as
  # External Secrets Operator, which is known as a ESO.
  # The term esos, comes from External Secrets Operators.
  # The pluralization of ESO.
  name: external-secrets-ollama
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: sage-ro
    kind: SecretStore
  target:
    name: ollama-authorized-tokens
  data:
# per user?
    - secretKey: AUTHORIZED_TOKENS
      remoteRef:
        key: sage/sage-ollama-vibe-coding-k8s
        property: AUTHORIZED_TOKENS_OLLAMA_ACCESS
