apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-fs
  namespace: {{ .Release.Namespace}}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 300Gi
