apiVersion: v1
kind: Service
metadata:
  name: service-ollama
  namespace: {{ .Release.Namespace }}
  labels:
    app: service-ollama
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "sage.code.assist.ollama.k8s.ucar.edu"
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  selector:
    app: deployment-ollama
  ports:
    - port: 11434
