apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: service-frontend
spec:
  selector:
    app: deployment-frontend
  ports:
    - port: 80
